# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherOS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=30)),
                ('Done', models.BooleanField(default=False)),
                ('Students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeacherOS.Student')),
            ],
        ),
    ]
